/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Product, Review } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'ring-01',
    nameKO: '실루엣 웨이브 실버 반지',
    nameEN: 'Silhouette Wave Silver Ring',
    price: 38000,
    category: 'ring',
    descriptionKO: '손가락을 부드럽게 감싸는 미세한 유선형 웨이브가 일상에 잔잔한 무드를 선사하는 실버 925 반지입니다. 심플하면서도 우아한 감성 디자인.',
    descriptionEN: 'A 925 sterling silver ring featuring a gentle organic wave that wraps around your finger, offering a subtle mood to your everyday look.',
    defaultImage: 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=800&auto=format&fit=crop&q=80',
    materialKO: '실버 925 (Sterling Silver)',
    materialEN: '925 Sterling Silver',
    options: {
      sizes: ['9호', '11호', '13호', '15호', '17호'],
      colors: ['Silver', 'Gold (+₩2,000)', 'Rose Gold (+₩2,000)'],
      hasEngraving: true
    }
  },
  {
    id: 'ring-02',
    nameKO: '미니멀 솔리드 하프 밴드',
    nameEN: 'Minimal Solid Half Band',
    price: 42000,
    category: 'ring',
    descriptionKO: '정교하게 폴리싱된 플랫한 표면과 묵직한 두께감이 조화를 이루어, 단독 착용은 물론 가이드 링과도 완벽히 레이어링되는 중성적 무드의 밴드.',
    descriptionEN: 'A high-polished flat flat flat band with moderate weight, perfectly designed for standalone styling or stacking with guide rings.',
    defaultImage: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&auto=format&fit=crop&q=80',
    materialKO: '실버 925 (Sterling Silver)',
    materialEN: '925 Sterling Silver',
    options: {
      sizes: ['11호', '13호', '15호', '17호', '19호', '21호'],
      colors: ['Silver', 'Gold (+₩3,000)'],
      hasEngraving: true
    }
  },
  {
    id: 'bracelet-01',
    nameKO: '드로잉 체인 토글 바 팔찌',
    nameEN: 'Drawing Chain Toggle Bar Bracelet',
    price: 54000,
    category: 'bracelet',
    descriptionKO: '손으로 그린 듯 자연스러운 형태의 라운드 루프 링크와 시그니처 토글 바 잠금 장치가 조화를 이룬 타임리스 리플렉션 팔찌입니다.',
    descriptionEN: 'A timeless reflection bracelet combining organic draft-round loop links with a signature toggle bar closure.',
    defaultImage: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800&auto=format&fit=crop&q=80',
    materialKO: '실버 925 (Sterling Silver)',
    materialEN: '925 Sterling Silver',
    options: {
      sizes: ['15cm', '16.5cm', '18cm'],
      colors: ['Silver', 'Gold (+₩4,000)'],
      hasEngraving: false
    }
  },
  {
    id: 'bracelet-02',
    nameKO: '슬림 플랫 위치 뱀줄 팔찌',
    nameEN: 'Slim Flat Snake Chain Bracelet',
    price: 46000,
    category: 'bracelet',
    descriptionKO: '피부에 주르륵 부드럽게 흐르며 메탈 본연의 반사광을 극대화하는 슬림 플랫 스네이크 체인 팔찌입니다. 데일리 레이어링 강력 추천.',
    descriptionEN: 'A liquid-like flat snake chain bracelet that flows smoothly on your skin, maximizing the natural metallic luster.',
    defaultImage: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?w=800&auto=format&fit=crop&q=80',
    materialKO: '실버 925 (Sterling Silver)',
    materialEN: '925 Sterling Silver',
    options: {
      sizes: ['15.5cm', '17cm'],
      colors: ['Silver', 'Gold (+₩3,000)', 'Rose Gold (+₩3,000)'],
      hasEngraving: false
    }
  },
  {
    id: 'keyring-01',
    nameKO: 'MINUA signature minua 커스텀 키링',
    nameEN: 'MINUA Signature minua Custom Keyring',
    price: 32000,
    category: 'keyring',
    descriptionKO: '미누아의 오리지널 "minua (미누아)" 커스텀 키링 모듈입니다. 나만의 기억, 영감, 그리고 패브릭 슬링이나 키 카드를 다양하게 엮으실 수 있습니다.',
    descriptionEN: 'MINUA`s original "minua (modular)" custom keyring module. Attach your daily inspirations, charms, and airpods smoothly.',
    defaultImage: '/images/keyring-01.svg',
    materialKO: '스틸 & 이탈리안 베지터블 레더 (Steel & Italian Veg Leather)',
    materialEN: 'Steel & Italian Vegetable Tanned Leather',
    options: {
      colors: ['Pure Black', 'Saddle Tan', 'Warm Taupe', 'Misty Olive'],
      charms: ['Silver Heart Charm (+₩5,000)', 'Leather Tag (Default)', 'Vintage Key (+₩6,000)', 'Logo Engraved Plate (+₩4,000)'],
      hasEngraving: true
    }
  },
  {
    id: 'keyring-02',
    nameKO: 'minua 매듭 서클 커넥터',
    nameEN: 'minua Knotted Circle Connector',
    price: 29000,
    category: 'keyring',
    descriptionKO: '수공예 가죽 스레드 매듭 디테일과 견고한 엔티크 서크 루프로 연결감을 한층 높인 minua 라인의 스테디셀러 커넥터 키링입니다.',
    descriptionEN: 'Steady-seller knot keyring from our minua lineup, combining handcrafted premium leather braids with matching raw-steel loops.',
    defaultImage: '/images/keyring-02.svg',
    materialKO: '황동 & 슈렁큰 소가죽 (Brass & Shrunken Leather)',
    materialEN: 'Solid Brass & Cowhide Leather',
    options: {
      colors: ['Antique Brass', 'Matt Chrome'],
      charms: ['Initial Coin (+₩4,000)', 'Mini Task Loop (+₩3,000)'],
      hasEngraving: true
    }
  },
  {
    id: 'gift-01',
    nameKO: '미누아 커플 리플렉트 링 세트',
    nameEN: 'MINUA Couple Reflect Ring Set',
    price: 76000,
    category: 'gift',
    descriptionKO: '소중한 연인과 함께 일상의 무드를 투영하여 영원히 간직할 수 있는 시그니처 쉐입 커플 은반지 2개 세트 상품입니다. 리본 선물 박스 기본 포장 포함.',
    descriptionEN: 'A signature design sterling silver pairing ring set for couples reflect your shared moments. Includes premium ribbon box wrapping.',
    defaultImage: 'https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=800&q=80',
    materialKO: '실버 925 (Sterling Silver)',
    materialEN: '925 Sterling Silver',
    options: {
      sizes: ['Option A (7호-23호)', 'Option B (7호-23호)'],
      colors: ['Silver Duet', 'Silver-Gold Duet (+₩5,000)'],
      hasEngraving: true
    }
  }
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    productId: 'ring-01',
    productName: '실루엣 웨이브 실버 반지',
    author: '김*인',
    rating: 5,
    content: '생각보다 실버 앤티크 분위기가 더 은은해서 매일 착용하기 너무 가볍고 예뻐요! 레이어드 링이랑 같이 끼면 시너지가 엄청 납니다. 강추해요~',
    createdAt: '2026-05-24'
  },
  {
    id: 'rev-2',
    productId: 'gift-01',
    productName: '미누아 커플 리플렉트 링 세트',
    author: '이*우',
    rating: 5,
    content: '커플링 1주년 기념으로 맞췄는데 포장이 정성 가득하고 리본 상자가 이뻐서 제대로 선물 한 느낌이 드네요. 은 재질 퀄리티도 우수하고 안쪽 이니셜 각인도 완벽합니다!',
    createdAt: '2026-06-02'
  },
  {
    id: 'rev-3',
    productId: 'keyring-01',
    productName: 'MINUA signature minua 커스텀 키링',
    author: 'Sarah K.',
    rating: 5,
    content: 'The "minua" custom detail concept is brilliant! I attached my vintage apartment key and a personal picture plate. Leather smell is gorgeous and looks super premium.',
    createdAt: '2026-06-05'
  }
];

export const DICTIONARY = {
  KO: {
    brandName: '미누아',
    brandTaglineLine1: '일상에 취향을 부착하다',
    brandTaglineLine2: 'minua는 매일 손에 닿는 작은 오브제에 사용자의 취향과 기억을 담아내는 브랜드입니다.',
    brandSubTagline: '반지, 팔찌, 키링처럼 가까이 지니는 아이템을 통해 일상 속 순간들이 나만의 분위기로 오래 남을 수 있도록 제안합니다.',
    menuHome: '홈',
    menuRing: '반지',
    menuBracelet: '팔찌',
    menuKeyring: '키링',
    menuGift: '커플 / 선물',
    menuAttStory: 'minua 스토리',
    menuReview: '리뷰',
    menuBrand: '브랜드 소개',
    menuMyPage: '마이 페이지',
    menuCart: '장바구니',
    btnBuyNow: '바로 구매',
    btnAddCart: '장바구니 보관',
    btnGiftWapping: '선물 포장 신청',
    productDetailTitle: '상품 상세 정보',
    materialLabel: '소재 정보',
    sizeLabel: '사이즈 선택',
    colorLabel: '색상 옵션',
    charmsLabel: 'minua 참(Charm) 추가',
    engravingLabel: '원하는 각인 문구',
    engravingPlaceholder: '영문/숫자 최대 10자 입력',
    sizeGuideTitle: '반지 사이즈가 고민이신가요?',
    sizeGuideText: '손가락 둘레를 종이나 실로 편안하게 한 바퀴 감싼 뒤, 맞닿는 부분을 잘라 자로 전체 길이를 재보세요. 아래 둘레와 가장 매치되는 사이즈를 호수로 선택해주세요. (9호: 52mm, 11호: 54mm, 13호: 56mm, 15호: 58mm, 17호: 60mm)',
    careGuideTitle: '주얼리 케어 및 제작 안내',
    careGuideText: '미누아의 모든 Silver 925 주얼리는 시간이 지나면서 자연스레 산화하여 특유의 클래식한 광택을 머금게 됩니다. 미착용 시 유입 공기가 적은 지퍼백에 밀봉 보관해주시면 오랜 시간 밝은 실버 상태를 보존할 수 있습니다. 앤티크 세척액이나 광천막으로 살살 문지르며 닦아주세요.',
    shippingGuideTitle: '배송 / 제작 알림',
    shippingGuideText: '고객님의 옵션 주문에 맞추어 개별 제작에 들어가는 맞춤형 주얼리의 경우, 영업일 기준 3 ~ 6일의 기획 및 마감 시간이 소요됩니다. 5만 원 이상 구매 시 국내 무료 배송 혜택이 적용됩니다.',
    attStoryTitle: 'minua (미누아) 스토리',
    attStoryIntroLine1: 'Attach Your Daily Moments.',
    attStoryIntroLine2: '미누아의 오리지널 부착 모듈형 액세서리 "minua(미누아)"는 주체적이고 자유로운 나날의 흐름을 반영합니다.',
    attStoryBody1: 'minua는 매일 손에 닿는 작은 오브제에 사용자의 취향과 기억을 담아내는 브랜드입니다.\n반지, 팔찌, 키링처럼 가까이 지니는 아이템을 통해 일상 속 순간들이 나만의 분위기로 오래 남을 수 있도록 제안합니다.',
    attStoryBody2: '지갑 속 가죽의 은은함, 손수 깎아 조각한 나무 참, 소중한 추억이 깃든 빈티지 하우스 키, 블루투스 오디오 케이스를 단단하게 체결하는 하나의 주축 고리가 되어줍니다.',
    attValueTitle1: '자유로운 커스텀 빌드',
    attValueDesc1: '하나의 베이스 포스트 링에 원하는 참(Charm)과 레더 스트랩, 오거나이저 키트를 언제든 레이어 구조로 추가하거나 탈거할 수 있어 질릴 틈 없는 감도를 자랑합니다.',
    attValueTitle2: '이탈리안 베지터블 레더',
    attValueDesc2: '수공예 태닝 과정을 거쳐 오랜 손때가 묻을수록 부드러워 지는 최고급 베지터블 천연 가죽만을 가닥마다 수놓아, 세월의 흐름과 자연스러운 에이징을 일상에서 시각화합니다.',
    attValueTitle3: '앤티크 프레임 스틸 하드웨어',
    attValueDesc3: '스너그하고 타이트한 잠금 장치 구조와 시간이 지나며 한층 더 고급스러움을 자아내는 크롬 도금 및 브라스 가공 마감을 통해 유실 없는 단단한 신뢰성을 유지합니다.',
    instaSubtitle: '손끝의 아름다움을 시각화하는 커뮤니티',
    instaClickGuide: '인스타그램 피드 연동 및 DM 실시간 주문/문의 연계 가능',
    reviewTitle: '고객 생생 후기',
    reviewSubtitle: '사용자들의 손길과 분위기가 깃든 솔직한 리뷰 모음',
    writeReviewBtn: '후기 남기기',
    writeReviewTitle: '새 리뷰 작성하기',
    ratingScore: '만족도 평점',
    reviewContent: '소중한 착용 후기를 들려주세요',
    uploadReviewPhoto: '착용 사진 파일 업로드 (선택)',
    submitReview: '리뷰 등록 완료',
    cartTitle: '선택하신 장바구니',
    emptyCart: '장바구니가 비어 있습니다. 감성적인 주얼리로 일상을 채워보세요!',
    totalPrice: '총 제품 금액',
    shippingFee: '배송료',
    freeShipping: '무료 배송 적용',
    subTotal: '최종 결제 금액',
    btnOrderNow: '주문서 작성 및 결제 단계',
    checkoutTitle: '주문자 정보 및 결제',
    senderName: '주문자/수령인 이름',
    senderPhone: '휴대전화 연락처',
    zipCode: '우편번호',
    addressInput: '거주지 기본 주소',
    addressDetail: '상세 건물/호수 입력',
    shippingMemo: '배송 요청 메시지 (선택)',
    paymentMethodLabel: '결제 방식 선택',
    payBankTransfer: '무통장 입금 (우리은행 1002-MINUA)',
    payKakao: '카카오페이 간편 주문',
    payCard: '해외 영수 결제 / 신용 카드 및 체크 카드',
    placeOrderBtn: '최종 결제 및 주문 생성',
    orderSuccessTitle: '주문이 완벽하게 접수되었습니다!',
    orderSuccessDesc: '작성하신 배송 주소지로 예쁘게 맞춤 제작하여 안심 발송해 드리겠습니다. 주문 고유 코드로 접수 상태를 실시간 확인하세요.',
    orderCodeLabel: '내 주문 고유 번호',
    myPageTitle: '나의 주문 처리 내역',
    myPageSubtitle: '미누아 회원 가입 / 비회원 로그인 상태 및 제작·배송 실시간 트래커',
    loginTitle: '로그인 및 주문 조회',
    loginDesc: '비회원 주문 확인 또는 데일리 적립 회원 로그인을 지원합니다.',
    emailLabel: '이메일 계정 주소',
    nameLabel: '성함 입력',
    btnLogin: '로그인 / 주문 관리 인입',
    btnLogout: '안전 로그아웃',
    newReg: '신규 에센셜 회원가입',
    statusPending: '주문 확인 중',
    statusPreparing: '제작 및 포장 작업 중',
    statusShipping: '안심 택배 배송 중',
    statusDelivered: '수령 완료 (예쁘게 착용하세요!)',
    giftWrapOptionTitle: '스페셜 포장 서비스 옵션',
    giftWrapBasic: '미누아 에센셜 린넨 주머니 클래식 패키징 (무료)',
    giftWrapPremium: '프리미엄 기프트 패킹 & 맞춤 실크 타이 리본 박스 (+₩5,000)',
    giftCardPlaceholder: '전달할 따뜻한 위로의 편지 문구를 적어주세요 (선물 동봉)',
    giftBannerTitle: '소중한 누군가를 위한 품격 있는 패키징 가이드',
    ownerPanelTitle: '[MINUA 매장 오너 전용] 실시간 이미지 커스텀 스튜디오',
    ownerPanelDesc: '“이미지는 내가 넣어주는 것들로만 해줘” 요건 충족: 하단의 배너 혹은 각 주얼리 상품 카드의 [이미지 직접 변경] 버튼을 통해 본인의 실제 키링/팔찌 주얼리 고품질 촬영 컷(JPG, PNG)을 즉각 교체 가능합니다! 올려주신 이미지는 브라우저 캐시에 완전 보관되어 완벽하고 독립적인 포토폴리오 사이트를 구축합니다.',
    uploadImageBtn: '내 촬영 이미지로 즉시 교체하기',
    uploadSuccessMsg: '성공적으로 오너님의 맞춤 주얼리 이미지가 대입되었습니다! 리얼 라이브 확인이 가능합니다.',
    instaDmInquiry: '인스타그램 DM 실시간 맞춤 수공 제작 문의',
    footerBizInfo: '(주) 미누아 크래프트 아틀리에 | 대표자: MINUA MASTER | 메일 문의: minua_jewelry@gmail.com | 서울시 종로구 세종대로 감성 주얼리 스튜디오 | 호스팅 서비스: AI Studio Cloud Container Sandbox Server',
    nonMemberAlert: '[안내] 가입 없이 비회원으로 메일 주소와 휴대전화 번호만 입력하셔도 바로 주문 및 조회가 가능합니다.'
  },
  EN: {
    brandName: 'MINUA',
    brandTaglineLine1: 'Attaching your personal taste to daily life.',
    brandTaglineLine2: 'minua is a brand that captures the wearer’s authentic taste and treasured memories in small everyday objects.',
    brandSubTagline: 'Through items held close to you, such as rings, bracelets, and keyrings, we suggest keeping your daily moments as your own unique atmosphere over a long time.',
    menuHome: 'Home',
    menuRing: 'Rings',
    menuBracelet: 'Bracelets',
    menuKeyring: 'Keyrings',
    menuGift: 'Couple & Gift',
    menuAttStory: 'minua Story',
    menuReview: 'Reviews',
    menuBrand: 'About Us',
    menuMyPage: 'My Orders',
    menuCart: 'Cart',
    btnBuyNow: 'Buy It Now',
    btnAddCart: 'Add To Cart',
    btnGiftWapping: 'Apply Gift Wrap',
    productDetailTitle: 'Product Features',
    materialLabel: 'Components & Material',
    sizeLabel: 'Size Selection',
    colorLabel: 'Color Options',
    charmsLabel: 'Add minua signature charms',
    engravingLabel: 'Request Personal Engraving',
    engravingPlaceholder: 'Letters / Numbers up to 10',
    sizeGuideTitle: 'Trouble picking the right ring size?',
    sizeGuideText: 'Simply wrap a fine string or long strip of paper snug around the base of your finger. Mark exactly where it overlaps and measure with a standard millimeter ruler. Choose the best matching size. (US 5/KR 9: 52mm, US 6/KR 11: 54mm, US 6.5/KR 13: 56mm, US 7.5/KR 15: 58mm, US 8/KR 17: 60mm)',
    careGuideTitle: 'Fine Jewelry Care Guideline',
    careGuideText: 'All MINUA sterling silver pieces tarnish organically over time due to contact with atmospheric air, creating a vintage customized patina. To retain bright metallic glow, seal in our air-tight zip pouches when not wearing. Polish occasionally with double-nap soft fabric cloths.',
    shippingGuideTitle: 'Handcrafted Production & Shipping',
    shippingGuideText: 'Since our master artisans individually forge and hand-finish each piece to match your specifications, custom jewelry requires 3 to 6 official business days before logistics dispatch.',
    attStoryTitle: 'Our Signature minua Story',
    attStoryIntroLine1: 'Attach Your Daily Moments.',
    attStoryIntroLine2: 'MINUA`s original dynamic attachment module, "minua", mirrors the free-flowing creative journeys of contemporary nomads.',
    attStoryBody1: 'minua is a brand that captures the wearer’s authentic taste and treasured memories in small everyday objects.\nThrough items held close to you, such as rings, bracelets, and keyrings, we suggest keeping your daily moments as your own unique atmosphere over a long time.',
    attStoryBody2: 'It blends raw metal key fobs, vegetable-tanned straps, modular car key adaptors, airpods leather sleeves, and handmade legacy keys into a singular unified design statement.',
    attValueTitle1: 'Dynamic Modular Config',
    attValueDesc1: 'Fasten or unclip curated charms, initial medals, and mini organizing pouches around a solid steel frame based on your lifestyle needs.',
    attValueTitle2: 'Signature Aged Veg-Skins',
    attValueDesc2: 'We hand-thread high-end vegetable tanned Italian hides that absorb hand oil and environmental elements to develop luxurious honey-hued deep colors.',
    attValueTitle3: 'Premium Antique Hardware',
    attValueDesc3: 'Secured via a high-tension precision tension latch. Finished in antique sand-blasted brass and satin chrome prevent accidental dropping.',
    instaSubtitle: 'Where aesthetic shapes meet individual wearers',
    instaClickGuide: 'Social community sync. Seamless Instagram direct messaging available',
    reviewTitle: 'Loved by Customers',
    reviewSubtitle: 'Sincere reviews reflecting the distinct mood of our real wearers',
    writeReviewBtn: 'Write a Review',
    writeReviewTitle: 'Write New Review',
    ratingScore: 'Rating Score',
    reviewContent: 'Tell us about your wearer experience',
    uploadReviewPhoto: 'Upload Wearer Image (Optional)',
    submitReview: 'Publish Review',
    cartTitle: 'Shopping Cart',
    emptyCart: 'Your cart is looking quiet. Let us fill it with sterling jewelry accents!',
    totalPrice: 'Items Cost',
    shippingFee: 'Shipping Fee',
    freeShipping: 'Complimentary Delivery',
    subTotal: 'Estimated Total',
    btnOrderNow: 'Proceed to Secure Checkout',
    checkoutTitle: 'Personal Clearance details',
    senderName: 'Recipient Full Name',
    senderPhone: 'Telephone Contact',
    zipCode: 'Postal Code',
    addressInput: 'Street Address',
    addressDetail: 'Appartement / Suite / Detail',
    shippingMemo: 'Logistic Courier Note (Optional)',
    paymentMethodLabel: 'Secure Payment Options',
    payBankTransfer: 'Bank Wire Transfer (Woori Bank 1002-MINUA)',
    payKakao: 'KakaoPay / Instant Wallet Order',
    payCard: 'International Standard Card Payment (Visa, Master)',
    placeOrderBtn: 'Execute Order & Create Log',
    orderSuccessTitle: 'Acknowledge: Order Completed Securely!',
    orderSuccessDesc: 'Our master craftsmen will begin forging based on requested customized choices. Live tracking is available via your ID.',
    orderCodeLabel: 'Simulated Tracking ID',
    myPageTitle: 'Live Order Tracker & History',
    myPageSubtitle: 'Review custom order crafting pipeline & shipping stages',
    loginTitle: 'Access Order Logs / Login',
    loginDesc: 'Login via individual e-mail credentials to review active shipping logs.',
    emailLabel: 'E-mail Clearance Account',
    nameLabel: 'User Full Name',
    btnLogin: 'Validate Credentials & Enter Portal',
    btnLogout: 'Secure Departure (Log Out)',
    newReg: 'Create Daily Essentials Account',
    statusPending: 'Checking Details',
    statusPreparing: 'Master Crafting & Packaging',
    statusShipping: 'In Secure Transit',
    statusDelivered: 'Delivered (Enjoy your gorgeous wear!)',
    giftWrapOptionTitle: 'Curated Packaging Selection',
    giftWrapBasic: 'MINUA Classic Air-mesh Linen Sac Packaging (Free)',
    giftWrapPremium: 'Premium Rigid Box Packing & Real Silk Grosgrain Ribbons (+₩5,000)',
    giftCardPlaceholder: 'Write a delicate card message to be custom typed on coordinate envelopes',
    giftBannerTitle: 'Exquisite Gift Wrap Architecture',
    ownerPanelTitle: '[MINUA Craft Studio Owner Dashboard]',
    ownerPanelDesc: 'Owner Upload Center: To completely honor "Use only images uploaded by me", click any [Change Image] trigger to upload your own premium product cuts or lifestyle jewelry images. It fully replaces static templates on-the-fly and saves to your local browser cache!',
    uploadImageBtn: 'Select Active Photo From Harddrive',
    uploadSuccessMsg: 'Image replaced successfully! Now rendering with your direct photographic files.',
    instaDmInquiry: 'Direct Message (DM) to Custom Order Handcrafted Pieces',
    footerBizInfo: 'MINUA Jewelry Workshop Co., Ltd. | Director: MINUA MASTER | Support: minua_jewelry@gmail.com | Sejong-daero, Jongno-gu, Seoul, Republic of Korea | Hosted via AI Studio Private Sandbox Node',
    nonMemberAlert: '[Notice] You can make fully tracked orders as a non-member simply by providing any casual e-mail address!'
  },
  JP: {
    brandName: 'ミヌア',
    brandTaglineLine1: '日常にこだわりを付着（アタッチ）する。',
    brandTaglineLine2: 'minuaは、毎日目に触れ、手で触れる小さなオブジェ에、使う人の好みや大切な記憶を宿すブランドです。',
    brandSubTagline: 'リング、ブレスレット、キーリングなど、いつも身近にあるアイテムを通じて、日常の何気ない瞬間が「自分だけの美しき空気感」として長く残るよう提案します。',
    menuHome: 'ホーム',
    menuRing: 'リング',
    menuBracelet: 'ブレスレット',
    menuKeyring: 'キーリング',
    menuGift: 'ペア / ギフト',
    menuAttStory: 'minuaストーリー',
    menuReview: 'レビュー',
    menuBrand: 'ブランドストーリー',
    menuMyPage: 'マイページ',
    menuCart: 'カート',
    btnBuyNow: '今すぐ購入',
    btnAddCart: 'カートに入れる',
    btnGiftWapping: 'ギフトラッピング申請',
    productDetailTitle: '商品の詳細情報',
    materialLabel: '素材情報',
    sizeLabel: 'サイズ選択',
    colorLabel: 'カラーオプション',
    charmsLabel: 'minua チャーム追加',
    engravingLabel: '刻印テキストのご要望',
    engravingPlaceholder: '英数字10文字以内',
    sizeGuideTitle: 'リングサイズでお悩みですか？',
    sizeGuideText: '糸や細長い紙を指의 太い部分にきつくなく、ぴったりと巻き付けてください。重なり合う部分に印をつけ、定規で長さをmm単位で測定します。測定値に最も近いサイズを号数でお選びください。（9号: 52mm, 11号: 54mm, 13号: 56mm, 15号: 58mm, 17号: 60mm）',
    careGuideTitle: 'ジュエリーのお手入れと製作案内',
    careGuideText: 'ミヌアのすべてのSilver 925ジュエリーは、時間の経過とともに自然に酸化し、独特のクラシックで上品な光沢を放つようになります。着用しないときは、空気の侵入を防ぐために密閉バッグに保管していただくと、明るいシルバーの状態を長く維持できます。シルバー専用のクロス等で優しく磨いてください。',
    shippingGuideTitle: '配送 / 製作に関するご案内',
    shippingGuideText: 'お客様のオーダーに合わせてマスター職人が手作業で1点ずつお作りするオーダーメイドジュエリーのため、ご注文から発送までに3〜6営業日（土日祝除く）の製作期間をいただいております。5,000円以上の購入で無料配送特典が適用されます。',
    attStoryTitle: 'minua (ミヌア) ストーリー',
    attStoryIntroLine1: 'Attach Your Daily Moments.',
    attStoryIntroLine2: 'ミヌアのシグネチャーアタッチメントモジュール「minua（ミヌア）」は、自由で創造的な日常のインスピレーションを形にします。',
    attStoryBody1: 'minuaは、毎日目に触れ、手で触れる小さなオブジェに、使う人の好みや大切な記憶を宿すブランドです。\nリング、ブレスレット、キーリングなど、いつも身近にあるアイテムを通じて、日常の何気ない瞬間が「自分だけの美しき空気感」として長く残るよう提案します。',
    attStoryBody2: 'イタリア製ベジタブルレザーの自然な風合い、温もりあるウッドチャーム、思い出の詰まったアンティークキー、エアポッズケースなどを美しく束ねる中心的な役割を果たします。',
    attValueTitle1: '自由なカスタムビルド',
    attValueDesc1: 'ベースポストリングに好みのチャームやレザーストラップ、ミニポーチなどをいつでも簡単に追加・取り外しでき、毎日の気分に合わせて自由に組み合わせられます。',
    attValueTitle2: 'イタルベジタブルレザーの美学',
    attValueDesc2: 'イタリアの伝統技術でなめされた最高級ベジタブルタンニンレザーを使用し、使い込むほどに手に馴染み、深みのある琥珀色へと経年変化する美しさをお楽しみいただけます。',
    attValueTitle3: 'アンティーク・スチール金具',
    attValueDesc3: '精密に設計された頑丈なラッチ構造と、使い込むことでアンティーク調の風合いが増すクロム・ブラス加工により、紛失のない強固な信頼性を提供します。',
    instaSubtitle: '指先の美しさを視覚化するコミュニティ',
    instaClickGuide: '公式SNSによる月間スタイリング情報の常時連動およびDM注文対応。',
    reviewTitle: 'お客様の着用レビュー',
    reviewSubtitle: '愛用者様の雰囲気と個性が輝く心のこもった着用レビュー。',
    writeReviewBtn: 'レビューを書く',
    writeReviewTitle: '新しいレビューを投稿する',
    ratingScore: '満足度評価',
    reviewContent: '着用感やデザインに関するご感想をお聞かせください',
    uploadReviewPhoto: '着用写真のアップロード（任意）',
    submitReview: 'レビューを登録する',
    cartTitle: 'ショッピングカート',
    emptyCart: '現在カートは空です。ミヌアの繊細な輝きで日常を彩ってみませんか？',
    totalPrice: '小計金額',
    shippingFee: '送料',
    freeShipping: '配送料無料',
    subTotal: 'お支払い金額合計',
    btnOrderNow: '注文書の作成とお支払いへ',
    checkoutTitle: 'ご注文者様情報とお支払い',
    senderName: 'お受取人様氏名',
    senderPhone: '携帯電話番号',
    zipCode: '郵便番号',
    addressInput: '基本住所',
    addressDetail: '番地・建物名・部屋番号',
    shippingMemo: '配送メモ・ご要望（任意）',
    paymentMethodLabel: '決済方法の選択',
    payBankTransfer: '銀行振込（みずほ銀行 1002-MINUA）',
    payKakao: '簡易スマートウォレット決済',
    payCard: 'クレジットカード・デビットカード決済',
    placeOrderBtn: '注文を確定してお支払い',
    orderSuccessTitle: 'ご注文が完了いたしました！',
    orderSuccessDesc: 'ご注文いただいた仕様に合わせて丁寧に手作りし、大切に発送いたします。追跡コードによりリアルタイムで製作・配送状況を追跡できます。',
    orderCodeLabel: 'ご注文番号 (追跡ID)',
    myPageTitle: 'ご注文追跡＆履歴',
    myPageSubtitle: '会員ログイン、無会員追跡、およびリアルタイムでの進行状況確認',
    loginTitle: 'ログイン・注文追跡',
    loginDesc: 'メールアドレスを使用し、現在のアクティブな注文や配送状況を確認できます。',
    emailLabel: 'メールアドレス',
    nameLabel: 'お名前',
    btnLogin: 'ログインして追跡開始',
    btnLogout: 'ログアウト（安全な終了）',
    newReg: '新規プレミアム会員登録',
    statusPending: '注文確認中',
    statusPreparing: '製作および梱包作業中',
    statusShipping: '安全に配送中',
    statusDelivered: '配達完了 (素敵な着用ライフをお楽しみください！)',
    giftWrapOptionTitle: 'スペシャル包装オプション',
    giftWrapBasic: 'ミヌアリネン巾着クラシックパッケージ (無料)',
    giftWrapPremium: 'プレミアムリボンボックス＆シルクタイパッケージギフト梱包 (+¥500)',
    giftCardPlaceholder: '大切な方へのオーダーメッセージをご記入レベルでお付けします（封筒同封）',
    giftBannerTitle: '上品なギフトラッピングのご案内',
    ownerPanelTitle: '[MINUA ショップオーナー専用] リアルタイム画像カスタムスタジオ',
    ownerPanelDesc: 'ご自身の実際の撮影画像(JPG/PNG)を、バナーや商品カードに即座に反映・変更できます！アップロードされた画像はローカルブラウザ의 キャッシュに保存され、独立したあなただけのポートフォリオサイトが構築されます。',
    uploadImageBtn: '写真を選んで変更する',
    uploadSuccessMsg: 'オーナー様のスタイリング写真に正常に差し替えられました。',
    instaDmInquiry: 'インスタグラムDMによる実時カスタムオーダー・お問い合わせ',
    footerBizInfo: '株式会社ミヌア・クラフト・アトリエ | 代表者: MINUA MASTER | サポート: minua_jewelry@gmail.com | 東京都港区クラフトスタジオ | ホスティングサーバー: AI Studio Private Cloud Container',
    nonMemberAlert: '[ご案内] 面倒な登録なしでも、メールアドレスと電話番号の入力だけで簡単にご注文・追跡が可能です。'
  }
};
